---
# Automatically uses Sub-folders to contain distro specific scrips
- include_tasks: '{{ ansible_os_family }}/{{ ansible_distribution }}/main.yml'

- debug:
    msg: "{{role_path | dirname}}"

- include_role:
    name: "{{role_path | dirname}}/sudo nopassword"
  when: sudoers
